URL_SERVICE = "https://6980b9d7-d4a0-4bdd-8044-c1be4467e5ca.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
CREATE_ORDERS = "/api/v1/orders/"
RECEIVE_ORDERS = "/api/v1/orders"
RECEIVE_ORDERS_TRACK ="/api/v1/orders/track"
LOG_MAIN_PATH = "/var/www/backend/logs/error.log"